# Use Node.js LTS
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy tsconfig and source
COPY tsconfig.json ./
COPY ./src ./src

# Expose port
EXPOSE 4000

# Start in dev mode with hot reload
CMD ["npm", "run", "start:dev"]
