name: Development PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Type check
        run: |
          cd frontend && pnpm tsc
          cd ../backend/api-gateway && pnpm tsc
          cd ../ai-service && pnpm tsc
          cd ../worker-service && pnpm tsc
          cd ../common && pnpm tsc

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose -f docker-compose.dev.yml build

      - name: Run Docker containers
        run: |
          docker compose -f docker-compose.dev.yml up -d
          sleep 30  # Wait for services to start

      - name: Test service health
        run: |
          curl -f http://localhost:3000 || exit 1
          curl -f http://localhost:4000/graphql || exit 1

      - name: Show Docker logs on failure
        if: failure()
        run: docker compose -f docker-compose.dev.yml logs

      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose.dev.yml down